# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
podfile: XCFitDemo/Podfile
before_install:
 - gem install danger
 - danger
#  - pod install --project-directory=XCFitDemo
script:
 - cd XCFitDemo/
 - pwd
 - set -o pipefail && xcodebuild -list
 - echo "==========Now Running Cucumberish Tests==================="
 - set -o pipefail && xcodebuild -project XCFitDemo.xcodeproj -scheme XCFitDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean build test | xcpretty -s -r html -r junit --color
 
